# -*- coding: utf-8 -*-
"""Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155KeTYwAR7pGOYjTV-HlpNqNNRelwqft
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

st.title("Bike Sharing Dashboard")
st.markdown("Dashboard analisis data penyewaan sepeda")

# Load data
df = pd.read_csv("dashboard/main_data.csv")

# Mapping label
season_map = {
    1: "Spring",
    2: "Summer",
    3: "Fall",
    4: "Winter"
}

weather_map = {
    1: "Clear",
    2: "Mist",
    3: "Light Snow/Rain",
    4: "Heavy Rain/Snow"
}

df["season"] = df["season"].map(season_map)
df["weathersit"] = df["weathersit"].map(weather_map)

# KPI
st.subheader("Total Penyewaan Sepeda")

total_rentals = df["cnt"].sum()

st.metric("Total Rental", value=int(total_rentals))

# Grafik Musim
st.subheader("Jumlah Penyewaan Sepeda Berdasarkan Musim")

season_rental = df.groupby("season")["cnt"].sum().reset_index()

fig, ax = plt.subplots()
sns.barplot(data=season_rental, x="season", y="cnt", ax=ax)

st.pyplot(fig)

# Grafik Cuaca
st.subheader("Jumlah Penyewaan Sepeda Berdasarkan Cuaca")

weather_rental = df.groupby("weathersit")["cnt"].sum().reset_index()

fig, ax = plt.subplots()
sns.barplot(data=weather_rental, x="weathersit", y="cnt", ax=ax)

st.pyplot(fig)

# Grafik Jam
st.subheader("Rata-rata Penyewaan Sepeda per Jam")

hourly_rental = df.groupby("hr")["cnt"].mean().reset_index()

fig, ax = plt.subplots()
sns.lineplot(data=hourly_rental, x="hr", y="cnt", marker="o", ax=ax)

st.pyplot(fig)

st.caption("Dashboard Analisis Bike Sharing Dataset")
